name: CI

on:
  - push

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc

      - run: npm ci

      - run: npx prettier --check .

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc

      - run: npm ci

      - run: |
          npx ng test --watch=false --browsers=ChromeHeadless
          npx ng test demo --watch=false --browsers=ChromeHeadless
          npx ng build demo

  build:
    runs-on: ubuntu-latest

    needs:
      - format
      - test

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc

      - run: npm ci

      - run: npx ng build ngx-exhaustive-check

      - uses: JS-DevTools/npm-publish@v3
        if: github.ref_name == 'main'
        id: publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./dist/ngx-exhaustive-check
          tag: latest
          access: public
          strategy: upgrade
